version: '2.4'
services:
  sci-viz:
    build: ./
    environment:
      CHOKIDAR_USEPOLLING: "true"
    image: web:v0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - main
networks:
  main: