name: Development
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run jest testing
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: yarn test
